
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://alexgalatoulas.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-41654103-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Alex Galatoulas"
title: "{ Alex Galatoulas }"
description: "Blog and website of Alex Galatoulas, blogging thoughts and ideas for sustainable thinking . Opinions expressed are mine."
keywords: "alex, galatoulas, civil engineering, ucl, city university, mottmacdonald, sustainable design, structural engineering, renewables, solar, eco homes, pv panels, energy efficiency, living building challenge, LBC, ILFI, Living future institute"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "What more can we do today..?"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#ffffff"
apple-status-bar-style: "white"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "alexgalatoulas"

syntax-highlight: False

############
# Timeline #
############

events:
  - image: "/img/timeline/GREECE_LBC_collaborative_logo_web1.jpg"
    date: "August 2016"
    description: "Official Launch of Living Building Challange Collaborative Greece.The Greek Collaborative strives to grow the roots of a framework for design, construction and symbiotic relationship between people and all aspects of the community in the built environment."
  - image: "/img/timeline/wca.png"
    date: "May 2016 - Today"
    description: "Stuctural Engineer worked on a major concrete frame refurbishmnet part of the Waterloo Regenaration Scheme. Secondment to Wessex Capacity Alliance on behalf of Mott Macdonald, an alliance of SKANSKA, Mott Macdonald, AECOM, Network Rail and Colas Rail"
  - image: "/img/timeline/mottmac.png"
    date: "September 2014 - Today"
    description: "Stuctural Engineer worked on major concrete frame refurbishment projects such as Belmont House Office in Uxbridge. I have also worked for the National Indoor Arena in Dublin and perform annual Maintenance and inspection report for Wembley National Stadium"
  - image: "/img/timeline/aibel.jpg"
    date: "December 2013 - Septemeber 2014"
    description: "Graduate Offshore Stuctural Engineer worked on the the GEMC complex in North Sea. The project scope was the modification and maintenance of the offshore platforms."
  - image: "/img/timeline/ucl.jpg"
    date: "September 2011 - August 2012"
    description: "M.Sc. Construction Economics & Management. I have been part of the Student Academic Representative team for the class."
  - image: "/img/timeline/city.jpg"
    date: "September 2006 - August 2011"
    description: "Graduated with an M.Eng (Hons) in Civil Engineering.High performance scholarship recipient for 2007 and 2008."

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "alexander.galatoulas@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Alex Galatoulas, is currently part of the Mott Macdonald structural engineering team in Buildings and Infrastructure department. Member of the Institution of Civil Engineers. Interested in sustainable development and creating engineering solutions that adding value to the social well being."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/alexandrosgalatoulas"
  - title: "twitter"
    url: "https://twitter.com/alexgalatoulas"
  - title: "pinterest"
    url: "https://pinterest.com/alexandergalato"
  - title: "rss"
    url: "/feed.xml"
  
############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
